# Generated by Django 6.0.8 on 2026-10-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('passport_data', models.CharField(max_length=50, unique=True, verbose_name='Паспортные данные')),
            ],
            options={
                'verbose_name': 'Хозяин',
                'verbose_name_plural': 'Хозяева',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст (лет)')),
                ('pedigree_number', models.CharField(max_length=50, unique=True, verbose_name='Номер родословной')),
                ('parent_names', models.CharField(max_length=255, verbose_name='Клички родителей')),
                ('last_vaccination_date', models.DateField(verbose_name='Дата последней прививки')),
                ('is_disqualified', models.BooleanField(default=False, verbose_name='Отстранена')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='core.breed', verbose_name='Порода')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='core.club', verbose_name='Клуб')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dogs', to='core.owner', verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_type', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('bronze', 'Бронза')], max_length=10, verbose_name='Тип медали')),
                ('awarded_at', models.DateField(verbose_name='Дата награждения')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medals', to='core.breed', verbose_name='Порода')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='core.dog', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер ринга')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rings', to='core.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Ринг',
                'verbose_name_plural': 'Ринги',
                'ordering': ['club', 'number'],
                'unique_together': {('club', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts', to='core.breed', verbose_name='Специализация (порода)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts', to='core.club', verbose_name='Клуб')),
                ('ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='core.ring', verbose_name='Ринг')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RingBreedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50, verbose_name='Временной слот')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.breed', verbose_name='Порода')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.ring', verbose_name='Ринг')),
            ],
            options={
                'verbose_name': 'Расписание ринга',
                'verbose_name_plural': 'Расписания рингов',
                'ordering': ['ring', 'time_slot'],
                'unique_together': {('ring', 'breed', 'time_slot')},
            },
        ),
    ]
